# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_teaching_kits'),
        ('activities', '0002_auto_20160818_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='country',
        ),
        migrations.AddField(
            model_name='activity',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='activities', to='authors.Author'),
        ),
        migrations.AddField(
            model_name='activity',
            name='locale',
            field=models.CharField(default='en-US', max_length=20),
        ),
        migrations.AddField(
            model_name='activityteachingkit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
