# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20160818_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='locale',
            field=models.CharField(blank=True, default='en-US', max_length=20),
        ),
    ]
