# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_auto_20160818_1854'),
        ('skills', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='image_retina_url',
            field=models.URLField(blank=True, help_text='URL to a retina quality image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to a regular quality image.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='competencies',
        ),
        migrations.AddField(
            model_name='skill',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='skills', to='competencies.Competency'),
        ),
    ]
