# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='text',
            field=models.TextField(),
        ),
    ]
