# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_kits', '0002_teachingkit'),
    ]

    operations = [
    ]
