# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_teaching_kits'),
        ('teaching_kits', '0003_auto_20160818_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingkit',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='teaching_kits', to='authors.Author'),
        ),
    ]
