# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_kits', '0004_teachingkit_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingkit',
            name='level',
        ),
        migrations.AlterField(
            model_name='teachingkit',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
