# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_kits', '0005_auto_20160818_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingkit',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Beginner mobile users', 'Beginner mobile users'), ('13+', '13+'), ('JavaScript beginners', 'JavaScript beginners')], default='Beginner', help_text='Difficulty levels for an activity', max_length=50),
        ),
    ]
