# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_auto_20160818_1854'),
        ('weblitskills', '0002_weblitskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblitskill',
            name='competencies',
        ),
        migrations.AddField(
            model_name='weblitskill',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='weblitskills', to='competencies.Competency'),
        ),
    ]
