# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblitskills', '0004_auto_20160818_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblitskill',
            name='competencies',
            field=models.ManyToManyField(blank=True, related_name='weblit_skills', to='competencies.Competency'),
        ),
        migrations.AlterField(
            model_name='weblitskill',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='weblit_skills', to='skills.Skill'),
        ),
    ]
