# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching_kits', '0002_teachingkit'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='URL to twitter or blog.', max_length=500, null=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='activities', to='authors.Activity')),
                ('teaching_kits', models.ManyToManyField(blank=True, related_name='teaching_kits', to='teaching_kits.TeachingKit')),
            ],
        ),
    ]
