# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_activity_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='activities',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
